In [1]:
import tensorflow as tf
from tensorflow import keras
import h5py
import cv2
from PIL import Image
import numpy

In [2]:
model = keras.models.load_model('Models\model05.h5')
imgCnt = 0

In [5]:
camera = cv2.VideoCapture(0)
for j in range(1):
    return_value, image = camera.read()
    cv2.imwrite('handgesture.png', image)
    img = Image.open('handgesture.png').convert('L')
    img = img.resize((300, 200))
    img.save('handgesturebw' + str(imgCnt) + '.png')
    imgCnt += 1
    img = Image.open('handgesturebw.png')
    np_img = numpy.array(img)
    np_img = np_img / 255.0
    x = numpy.expand_dims(np_img, axis=0)
    x = numpy.expand_dims(x, axis=3)
    print(x)
    pred = model.predict(x)
    print(pred*100)
    for i in range(3):
        if pred[0][i]*100 > 50:
            if i == 0:
                print("Scissors")
            elif i == 1:
                print("Paper")
            elif i == 2:
                print("Rock")
            break
del(camera)

[[[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]]
[[1.2892221e-02 9.0753799e+01 9.2332993e+00]]
Paper


In [4]:
imgCnt

1

In [6]:
import requests
import cv2

content_type = 'image/jpeg'
headers = {'content-type': content_type}
img = cv2.imread('handgesture.png')
img = cv2.resize(img, (300, 200)) 
img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
_, img_encoded = cv2.imencode('.jpg', img)

response = requests.post('http://192.168.1.55:5000/detectGesture', data=img_encoded.tostring(), headers=headers)

print(response.content)

b'"Paper"'
